.TH WAYNEKO 1 2023-08-14 "git.sr.ht/~leon_plickat/wayneko" "General Commands Manual"
.
.SH NAME
.P
wayneko \- Neko on Wayland
.
.
.SH SYNOPSIS
.SY wayneko
.OP \-h
.OP \-\-help
.OP \-?
.YS
.
.SY wayneko
.OP \-\-background\-colour 0xRRGGBB[AA]
.OP \-\-outline\-colour 0xRRGGBB[AA]
.OP \-\-type neko|inu|random
.OP \-\-follow\-pointer true|false
.OP \-\-survive\-close
.YS
.
.
.SH DESCRIPTION
.P
Display an animated neko cat on the bottom of an output.
Responds to the pointer being near the bottom edge of that output.
While most cats are usually active at night, wayneko likes to mostly sleep when
it's late, only occasionally waking.
.P
Requires the Wayland server to implement \fBzwlr-layer-shell-unstable-v1\fR.
.
.
.SH OPTIONS
.P
\fB\-h\fR, \fB\-\-help\fR, \fB\-?\fR
.RS
Print help text and exit.
.RE
.
.P
\fB\-\-background\-colour\fR \fI0xRRGGBB[AA]\fR
.RS
Set the background fill colour using a hexadecimal colour code prefixed by '0x'.
Alpha value is optional.
.RE
.
.P
\fB\-\-outline\-colour\fR \fI0xRRGGBB[AA]\fR
.RS
Set the outline colour using a hexadecimal colour code prefixed by '0x'.
Alpha value is optional.
.RE
.
.P
\fB\-\-type\fR \fBneko\fR|\fBinu\fR|\fBrandom\fR
.RS
This option lets you choose between neko and her friend inu.
.RE
.
.P
\fB\-\-follow\-pointer\fR \fBtrue\fR|\fBfalse\fR
.RS
Set whether neko follows the pointer when it approaches the bottom of the output
.RE
.
.P
\fB\-\-survive\-close\fR
.RS
If this flag is used, wayneko will recreate the surface after it has been closed.
This allows neko to migrate outputs should the one she is currently on be
disconnected, but may cause some undesired behaviour should the server try to
close the surface for a different reason.
.RE
.
.
.SH AUTHOR
.P
Code by
.MT leonhenrik.plickat@stud.uni-goettingen.de
Leon Henrik Plickat
.ME .
.
.P
Neko bitmaps taken from public domain.
